// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzzkhqvS99Pq-gDJ4sigRGaINima57Po',
    appId: '1:715082149329:web:41c313c6138ef95b0204f0',
    messagingSenderId: '715082149329',
    projectId: 'finance-app-d1e35',
    authDomain: 'finance-app-d1e35.firebaseapp.com',
    storageBucket: 'finance-app-d1e35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1ATJUgfOY9f5EdfyWIprJpVEMjh6INc',
    appId: '1:715082149329:android:ce9065d3a5885d5b0204f0',
    messagingSenderId: '715082149329',
    projectId: 'finance-app-d1e35',
    storageBucket: 'finance-app-d1e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVn6EWsWURwinB5QI4WdQdXkovE6a0j8o',
    appId: '1:715082149329:ios:db1f8ecb3311289f0204f0',
    messagingSenderId: '715082149329',
    projectId: 'finance-app-d1e35',
    storageBucket: 'finance-app-d1e35.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVn6EWsWURwinB5QI4WdQdXkovE6a0j8o',
    appId: '1:715082149329:ios:db1f8ecb3311289f0204f0',
    messagingSenderId: '715082149329',
    projectId: 'finance-app-d1e35',
    storageBucket: 'finance-app-d1e35.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVzzkhqvS99Pq-gDJ4sigRGaINima57Po',
    appId: '1:715082149329:web:582f5c8d2e4178a00204f0',
    messagingSenderId: '715082149329',
    projectId: 'finance-app-d1e35',
    authDomain: 'finance-app-d1e35.firebaseapp.com',
    storageBucket: 'finance-app-d1e35.firebasestorage.app',
  );
}
