import 'package:flutter/material.dart';

final List<IconData> availableIcons = [
  Icons.money_outlined,
  Icons.house_outlined,
  Icons.shopping_cart_outlined,
  Icons.health_and_safety_outlined,
  Icons.theater_comedy_outlined,
  Icons.coffee_outlined,
  Icons.restaurant_outlined,
  Icons.local_taxi_outlined,
  Icons.bed_outlined,
  Icons.shopping_bag_outlined,
  Icons.language_outlined,
  Icons.redeem_outlined,
  Icons.airplanemode_active_outlined,
  Icons.local_gas_station_outlined,
  Icons.local_atm_outlined,
  Icons.train_outlined,
  Icons.book_outlined,
  Icons.child_friendly_outlined,
  Icons.directions_car_outlined,
  Icons.movie_outlined,
  Icons.pets_outlined,
  Icons.computer_outlined,
  Icons.brush_outlined,
  Icons.directions_bike_outlined,
  Icons.fitness_center_outlined,
  Icons.event_outlined,
  Icons.spa_outlined,
  Icons.wine_bar_outlined,
  Icons.local_library_outlined,
  Icons.savings_outlined,
  Icons.cake_outlined,
  Icons.park_outlined,
  Icons.sports_soccer_outlined,
  Icons.work_outline,
  Icons.home_repair_service_outlined,
  Icons.hiking_outlined,
  Icons.music_note_outlined,
  Icons.pool_outlined,
  Icons.videogame_asset_outlined,
  Icons.travel_explore_outlined,
  Icons.handyman_outlined,
  Icons.bolt_outlined,
  Icons.nightlife_outlined,
  Icons.surfing_outlined,
  Icons.tips_and_updates_outlined,
];

List<IconData> icons = [
  Icons.money_outlined,
  Icons.house_outlined,
  Icons.shopping_cart_outlined,
  Icons.health_and_safety_outlined,
  Icons.theater_comedy_outlined, //entertainment
  Icons.coffee_outlined,
  Icons.restaurant_outlined,
  Icons.local_taxi_outlined,
  Icons.bed_outlined,
  Icons.shopping_bag_outlined,
  Icons.language_outlined,
  Icons.redeem_outlined,
  Icons.airplanemode_active_outlined,
  Icons.local_gas_station_outlined,
  Icons.local_atm_outlined,

  Icons.train_outlined,
  Icons.book_outlined,
  Icons.child_friendly_outlined,
  Icons.directions_car_outlined,
  Icons.movie_outlined,
  Icons.pets_outlined,
  Icons.computer_outlined,
  Icons.brush_outlined,
  Icons.directions_bike_outlined,
  Icons.fitness_center_outlined,
  Icons.event_outlined,
  Icons.spa_outlined,
  Icons.wine_bar_outlined,
  Icons.local_library_outlined,
  Icons.savings_outlined,
  Icons.cake_outlined,
  Icons.park_outlined,
  Icons.sports_soccer_outlined,
  Icons.work_outline,
  Icons.home_repair_service_outlined,
  Icons.hiking_outlined,
  Icons.music_note_outlined,
  Icons.pool_outlined,
  Icons.videogame_asset_outlined,
  Icons.travel_explore_outlined,
  Icons.handyman_outlined,
  Icons.bolt_outlined,
  Icons.nightlife_outlined,
  Icons.surfing_outlined,
  Icons.tips_and_updates_outlined,

  Icons.beach_access_outlined, //drzewko wakacje
  Icons.add_outlined,
  Icons.route_outlined,

  /// zmienić na dobre switche bo to chyba nie to
  Icons.person_outlined,
  Icons.apps_outlined,
  Icons.filter_alt_outlined,
  Icons.notification_add_outlined,
  Icons.notifications_outlined,
  Icons.calendar_month_outlined,
  Icons.delete_outlined,
  Icons.clear_outlined,
  Icons.chevron_right_outlined,
  Icons.more_horiz_outlined,
  Icons.chevron_left_outlined,
  Icons.question_mark_outlined,
  Icons.contrast_outlined,
  Icons.logout_outlined,
  Icons.privacy_tip_outlined,
  Icons.lock_outline,
  Icons.credit_card_outlined,
  Icons.note_outlined,
  Icons.photo_camera_outlined,
  Icons.folder_copy_outlined,
  Icons.attach_money_outlined,
  Icons.search_outlined,
  Icons.info_outline,

  Icons.settings_outlined,
  Icons.settings,
  Icons.equalizer_outlined,
  Icons.equalizer,
  Icons.grid_view_outlined,
  Icons.grid_view_sharp,
  Icons.savings_outlined,
  Icons.savings,
  Icons.visibility_off_outlined,
  Icons.visibility_outlined,

  Icons.tune_outlined //general
];
